### ISSUE TITLE
Error when installing dependencies, in Unit 8 part 1.

### ISSUE THREAD

**Issue by joaopedrosdmm** [huggingface/deep-rl-class#272]
I think it is a version problem, but I'm not sure. 

collecting gym==0.21
  Downloading gym-0.21.0.tar.gz (1.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 40.0 MB/s eta 0:00:00
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: imageio-ffmpeg in /usr/local/lib/python3.9/dist-packages (0.4.8)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting huggingface_hub
  Downloading huggingface_hub-0.13.3-py3-none-any.whl (199 kB)

**Comment by simoninithomas** [comment]
Hey there 👋 I just updated the notebook it should work now 🤗

**Comment by joaopedrosdmm** [comment]
Still not working. 

Now it looks like there are multiple errors in the provided traceback. The first warning indicates that TensorFlow-TensorRT (TF-TRT) was unable to find TensorRT.

Int the second error It looks like the script is trying to create a Box2D environment, but is encountering an error when importing the Box2D library. This could be due to a version incompatibility between the Box2D library and the version of Python or other libraries being used.

I will try to update Box2D library to the latest version, or downgrading to a version that is compatible with the version of Python and other libraries you are using. 

Error log:

`
2023-04-06 11:11:36.352338: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/content/ppo.py", line 413, in <module>
    envs = gym.vector.SyncVectorEnv(
  File "/usr/local/lib/python3.9/dist-packages/gym/vector/sync_vector_env.py", line 34, in __init__
    self.envs = [env_fn() for env_fn in env_fns]
  File "/usr/local/lib/python3.9/dist-packages/gym/vector/sync_vector_env.py", line 34, in <listcomp>
    self.envs = [env_fn() for env_fn in env_fns]
  File "/content/ppo.py", line 335, in thunk
    env = gym.make(env_id)
  File "/usr/local/lib/python3.9/dist-packages/gym/envs/registration.py", line 235, in make
    return registry.make(id, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/gym/envs/registration.py", line 129, in make
    env = spec.make(**kwargs)
  File "/usr/local/lib/python3.9/dist-packages/gym/envs/registration.py", line 89, in make
    cls = load(self.entry_point)
  File "/usr/local/lib/python3.9/dist-packages/gym/envs/registration.py", line 27, in load
    mod = importlib.import_module(mod_name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/dist-packages/gym/envs/box2d/__init__.py", line 2, in <module>
    import Box2D
  File "/usr/local/lib/python3.9/dist-packages/Box2D/__init__.py", line 20, in <module>
    from .Box2D import *
  File "/usr/local/lib/python3.9/dist-packages/Box2D/Box2D.py", line 435, in <module>
    _Box2D.RAND_LIMIT_swigconstant(_Box2D)
AttributeError: module '_Box2D' has no attribute 'RAND_LIMIT_swigconstant'
`

**Comment by gianmarcocr** [comment]
i have the same problem:
my output
```Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting gym==0.21
  Downloading gym-0.21.0.tar.gz (1.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 63.2 MB/s eta 0:00:00
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: imageio-ffmpeg in /usr/local/lib/python3.9/dist-packages (0.4.8)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting huggingface_hub
  Downloading huggingface_hub-0.13.4-py3-none-any.whl (200 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 200.1/200.1 KB 15.9 MB/s eta 0:00:00
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.9/dist-packages (from huggingface_hub) (23.0)
Requirement already satisfied: requests in /usr/local/lib/python3.9/dist-packages (from huggingface_hub) (2.27.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.9/dist-packages (from huggingface_hub) (4.5.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.9/dist-packages (from huggingface_hub) (6.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.9/dist-packages (from huggingface_hub) (3.10.7)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.9/dist-packages (from huggingface_hub) (4.65.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.9/dist-packages (from requests->huggingface_hub) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.9/dist-packages (from requests->huggingface_hub) (1.26.15)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.9/dist-packages (from requests->huggingface_hub) (2.0.12)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.9/dist-packages (from requests->huggingface_hub) (2022.12.7)
Installing collected packages: huggingface_hub
Successfully installed huggingface_hub-0.13.4
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting box2d
  Downloading Box2D-2.3.2.tar.gz (427 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 427.9/427.9 KB 10.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: box2d
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for box2d (setup.py) ... error
  ERROR: Failed building wheel for box2d
  Running setup.py clean for box2d
Failed to build box2d
Installing collected packages: box2d
  error: subprocess-exited-with-error
  
  × Running setup.py install for box2d did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Running setup.py install for box2d ... error
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> box2d

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.```

**Comment by joaopedrosdmm** [comment]
Hey, just solved the issue.

When installing all the packages, change "!pip install box2d", with "!pip install box2d-py==2.3.8"
