### ISSUE TITLE
[HANDS-ON BUG]unit2:FileNotFoundError: [Errno 2] No such file or directory: 'Xvfb'

### ISSUE THREAD

**Issue by jakezou** [huggingface/deep-rl-class#381]
# Describe the bug

**Please share your notebook link so that we can reproduce the error**

# Material

 - Did you use Google Colab?

If not:
 - Your Operating system (OS)
 - Version of your OS

**Comment by jakezou** [comment]
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
[<ipython-input-1-6a8c1d860fe4>](https://localhost:8080/#) in <cell line: 4>()
      2 from pyvirtualdisplay import Display
      3 
----> 4 virtual_display = Display(visible=0, size=(1400, 900))
      5 virtual_display.start()

5 frames
[/usr/lib/python3.10/subprocess.py](https://localhost:8080/#) in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, restore_signals, gid, gids, uid, umask, start_new_session)
   1861                     if errno_num != 0:
   1862                         err_msg = os.strerror(errno_num)
-> 1863                     raise child_exception_type(errno_num, err_msg, err_filename)
   1864                 raise child_exception_type(err_msg)
   1865 

FileNotFoundError: [Errno 2] No such file or directory: 'Xvfb'

**Comment by simoninithomas** [comment]
Hey there 👋 

Thanks for pointing this out it was a bug I thought was resolved last time #275 but I forgot to push the new notebook. It's now done.

**Comment by miklewis** [comment]
simoninithomas-
I am still encountering exactly the same problem in colab reported by jakezou

**Comment by simoninithomas** [comment]
@miklewis did you run the notebook and reopen it after for the second part? Xvfb is quite unstable sometime with colab the best solution is to reset the notebook 😩.

**Comment by miklewis** [comment]
@simoninithomas Thanks for responding so rapidly!  I've tried reopening the
notebook & resetting the runtime several times but with the same result.
The code is intended to set up tensorboard.  This was working last fall.
# Visualization utils
%load_ext tensorboard
import sys
from tqdm.notebook import trange
!pip install tensorboardx gym pyvirtualdisplay
!apt-get install -y xvfb python-opengl  ffmpeg
The last line fails with result appearing when program attempts to
initialize a virtual display for tensorboard output
# Virtual display
from pyvirtualdisplay import Display
virtual_display = Display(visible=0, size=(1400, 900))

Error appears as:

E: Unable to locate package python-opengl

---------------------------------------------------------------------------

FileNotFoundError                         Traceback (most recent call last)

<ipython-input-1-3a106e665c21> <https://localhost:8080/#> in <cell
line: 25>()     23 from pyvirtualdisplay import Display     24
---> 25 virtual_display = Display(visible=0, size=(1400, 900))


/usr/lib/python3.10/subprocess.py <https://localhost:8080/#> in
_execute_child(self, args, executable, preexec_fn, close_fds,
pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread,
p2cwrite, c2pread, c2pwrite, errread, errwrite, restore_signals, gid,
gids, uid, umask, start_new_session)   1861                     if
errno_num != 0:   1862                         err_msg =
os.strerror(errno_num)
-> 1863                     raise child_exception_type(errno_num,
err_msg, err_filename)   1864                 raise
child_exception_type(err_msg)   1865

FileNotFoundError: [Errno 2] No such file or directory: 'Xvfb'

Which appears to be the same/similar error being reported by @jakezou

**Comment by simoninithomas** [comment]
What's the notebook?

**Comment by miklewis** [comment]
I am sorry for not responding sooner.  Xvfb problem was unsatisfyingly
resolved by breaking the install into parts replacing:
'!apt-get install -y xvfb python-opengl ffmpeg'
with
'!apt-get install  xvfb
!apt-get install python-opengl ffmpeg'

**Comment by simoninithomas** [comment]
Hey there 👋 no problem 😄 I'm adding this to the next update to be more clear on how to install xvfb on different platform (colab, vm, computer)
